---
- name: install utilites
  hosts: all
  tasks: 
    - name: Install ntpdate
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      become: yes  
      loop: "{{ packages }}"
